export const STAGES = [
  {
    minStairs: 0,
    title: '볼살 햄찌',
    subtitle: '쳇바퀴는 장식이야',
    stageLabel: 'STAGE 1',
    luTitle: '쳇바퀴 앞에 섰다!',
    luDesc: '드디어 쳇바퀴 앞에 섰다',
    image: require('../../assets/hamster_1.png'),
    bgImage: require('../../assets/bg_1.png'),
  },
  {
    minStairs: 10,
    title: '굴러보는 햄찌',
    subtitle: '일단 굴러봄',
    stageLabel: 'STAGE 2',
    luTitle: '일단 굴러봄!',
    luDesc: '볼이 오른쪽으로 굴러감',
    image: require('../../assets/hamster_2.png'),
    bgImage: require('../../assets/bg_2.png'),
  },
  {
    minStairs: 30,
    title: '달리는 햄찌',
    subtitle: '쳇바퀴 속도 올림',
    stageLabel: 'STAGE 3',
    luTitle: '속도가 붙었다!',
    luDesc: '쳇바퀴가 점점 빨라진다',
    image: require('../../assets/hamster_3.png'),
    bgImage: require('../../assets/bg_3.png'),
  },
  {
    minStairs: 60,
    title: '근육 햄찌',
    subtitle: '멈출 수가 없어',
    stageLabel: 'STAGE 4',
    luTitle: '근육이 생겼다!',
    luDesc: '배가 쏙 들어갔다',
    image: require('../../assets/hamster_4.png'),
    bgImage: require('../../assets/bg_4.png'),
  },
  {
    minStairs: 100,
    title: '전설의 햄찌',
    subtitle: '쳇바퀴를 부숨',
    stageLabel: 'STAGE 5',
    luTitle: '전설 달성!!',
    luDesc: '쳇바퀴를 때려부숨!',
    image: require('../../assets/hamster_5.png'),
    bgImage: require('../../assets/bg_5.png'),
  },
  {
    minStairs: 150,
    title: '헤드밴드 햄찌',
    subtitle: '운동이 취미가 됨',
    stageLabel: 'STAGE 6',
    luTitle: '운동이 취미가 됐다!',
    luDesc: '헤드밴드를 찼다',
    locked: true,
    image: require('../../assets/hamster_6.png'),
    bgImage: require('../../assets/bg_6.png'),
  },
  {
    minStairs: 200,
    title: '레깅스 햄찌',
    subtitle: '레깅스를 샀어',
    stageLabel: 'STAGE 7',
    luTitle: '레깅스 구매 완료!',
    luDesc: '이제 진짜 운동인이다',
    locked: true,
    image: require('../../assets/hamster_7.png'),
    bgImage: require('../../assets/bg_7.png'),
  },
  {
    minStairs: 250,
    title: '아령 햄찌',
    subtitle: '근육이 생긴 것 같기도',
    stageLabel: 'STAGE 8',
    luTitle: '근육이 생겼다!',
    luDesc: '아령을 들기 시작했다',
    locked: true,
    image: require('../../assets/hamster_8.png'),
    bgImage: require('../../assets/bg_8.png'),
  },
  {
    minStairs: 300,
    title: '금메달 햄찌',
    subtitle: '주변에서 이상한 눈으로 봄',
    stageLabel: 'STAGE 9',
    luTitle: '금메달 획득!!',
    luDesc: '층층이 올림픽 선수',
    locked: true,
    image: require('../../assets/hamster_9.png'),
    bgImage: require('../../assets/bg_9.png'),
  },
  {
    minStairs: 350,
    title: '왕관 햄찌',
    subtitle: '계단이 나를 두려워함',
    stageLabel: 'FINAL',
    luTitle: '계단왕 등극!!',
    luDesc: '계단이 나를 두려워한다',
    locked: true,
    image: require('../../assets/hamster_10.png'),
    bgImage: require('../../assets/bg_10.png'),
  },
];
