export const STAGES = [
  {
    minStairs: 0,
    title: '볼살 햄찌',
    subtitle: '쳇바퀴는 장식이야',
    stageLabel: 'STAGE 1',
    luTitle: '쳇바퀴 앞에 섰다!',
    luDesc: '드디어 쳇바퀴 앞에 섰다',
    image: require('../../assets/hamster_1.png'),
  },
  {
    minStairs: 100,
    title: '굴러보는 햄찌',
    subtitle: '일단 굴러봄',
    stageLabel: 'STAGE 2',
    luTitle: '일단 굴러봄!',
    luDesc: '볼이 오른쪽으로 굴러감',
    image: require('../../assets/hamster_2.png'),
  },
  {
    minStairs: 300,
    title: '달리는 햄찌',
    subtitle: '쳇바퀴 속도 올림',
    stageLabel: 'STAGE 3',
    luTitle: '속도가 붙었다!',
    luDesc: '쳇바퀴가 점점 빨라진다',
    image: require('../../assets/hamster_3.png'),
  },
  {
    minStairs: 700,
    title: '근육 햄찌',
    subtitle: '멈출 수가 없어',
    stageLabel: 'STAGE 4',
    luTitle: '근육이 생겼다!',
    luDesc: '배가 쏙 들어갔다',
    image: require('../../assets/hamster_4.png'),
  },
  {
    minStairs: 1500,
    title: '전설의 햄찌',
    subtitle: '쳇바퀴를 부숨',
    stageLabel: 'FINAL',
    luTitle: '전설 달성!!',
    luDesc: '쳇바퀴를 때려부숨!',
    image: require('../../assets/hamster_5.png'),
  },
];
