export const STAGES = [
  {
    minStairs: 0,
    title: '볼살 햄찌',
    subtitle: '쳇바퀴는 그냥 인테리어야',
    stageLabel: 'STAGE 1',
    luTitle: '일어나긴 했다',
    luDesc: '쳇바퀴 앞까지는 왔어',
    image: require('../../assets/hamster_1.png'),
    bgImage: require('../../assets/bg_1.png'),
  },
  {
    minStairs: 10,
    title: '굴러보는 햄찌',
    subtitle: '일단 한 바퀴는 굴렀음',
    stageLabel: 'STAGE 2',
    luTitle: '굴러봤다!',
    luDesc: '멈추는 법을 잊었어',
    image: require('../../assets/hamster_2.png'),
    bgImage: require('../../assets/bg_2.png'),
  },
  {
    minStairs: 30,
    title: '달리는 햄찌',
    subtitle: '이거 은근 재밌는데?',
    stageLabel: 'STAGE 3',
    luTitle: '속도가 붙었다!',
    luDesc: '쳇바퀴가 점점 신나진다',
    image: require('../../assets/hamster_3.png'),
    bgImage: require('../../assets/bg_3.png'),
  },
  {
    minStairs: 60,
    title: '근육 햄찌',
    subtitle: '멈추면 어색해',
    stageLabel: 'STAGE 4',
    luTitle: '배가 쏙 들어갔다!',
    luDesc: '볼살이 조금 빠진 것 같기도',
    image: require('../../assets/hamster_4.png'),
    bgImage: require('../../assets/bg_4.png'),
  },
  {
    minStairs: 100,
    title: '전설의 햄찌',
    subtitle: '쳇바퀴가 나한테 맞춤',
    stageLabel: 'STAGE 5',
    luTitle: '쳇바퀴를 때려부쉈다!!',
    luDesc: '이제 진짜 시작이야',
    image: require('../../assets/hamster_5.png'),
    bgImage: require('../../assets/bg_5.png'),
  },
  {
    minStairs: 150,
    title: '헤드밴드 햄찌',
    subtitle: '운동복을 사기 시작함',
    stageLabel: 'STAGE 6',
    luTitle: '헤드밴드 장착 완료!',
    luDesc: '이제 외형도 운동인',
    locked: true,
    image: require('../../assets/hamster_6.png'),
    bgImage: require('../../assets/bg_6.png'),
  },
  {
    minStairs: 200,
    title: '레깅스 햄찌',
    subtitle: '레깅스 입고 나왔더니 다들 쳐다봄',
    stageLabel: 'STAGE 7',
    luTitle: '레깅스 구매 완료!',
    luDesc: '뒤태가 달라졌다',
    locked: true,
    image: require('../../assets/hamster_7.png'),
    bgImage: require('../../assets/bg_7.png'),
  },
  {
    minStairs: 250,
    title: '아령 햄찌',
    subtitle: '아령이 가볍게 느껴짐',
    stageLabel: 'STAGE 8',
    luTitle: '근육이 생겼다!',
    luDesc: '볼살인 줄 알았는데 근육이었어',
    locked: true,
    image: require('../../assets/hamster_8.png'),
    bgImage: require('../../assets/bg_8.png'),
  },
  {
    minStairs: 300,
    title: '금메달 햄찌',
    subtitle: '주변 햄찌들이 피하기 시작함',
    stageLabel: 'STAGE 9',
    luTitle: '금메달 획득!!',
    luDesc: '계단 올림픽 국가대표',
    locked: true,
    image: require('../../assets/hamster_9.png'),
    bgImage: require('../../assets/bg_9.png'),
  },
  {
    minStairs: 350,
    title: '왕관 햄찌',
    subtitle: '계단이 나를 두려워한다',
    stageLabel: 'FINAL',
    luTitle: '건강왕 등극!!',
    luDesc: '뱃살이 뭔지 잊어버렸다',
    locked: true,
    image: require('../../assets/hamster_10.png'),
    bgImage: require('../../assets/bg_10.png'),
  },
];
